[project]
name = "priceanalysis"
version = "0.1.0"
description = ""
authors = [
    {name = "ATISHAY JAIN",email = "atishayj.dev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "statsmodels",
    "scikit-learn",
    "plotly",
    "openpyxl"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
